spring.application.name=salary-service
server.port=${SERVER_PORT:8082}

# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql:/localhost:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres.jtifherhrrfrsdtulinc}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=salary
spring.jpa.show-sql=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.example.salaryservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
