spring.application.name=vote-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/salarydb?currentSchema=community}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=community
spring.jpa.open-in-view=false
vote.threshold=${VOTE_THRESHOLD:3}
salary.service.url=${SALARY_SERVICE_URL:http://localhost:8082}
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
