apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  SPRING_DATASOURCE_USERNAME: admin
  IDENTITY_SERVICE_URL: http://identity-service:8081
  SALARY_SERVICE_URL: http://salary-service:8082
  VOTE_SERVICE_URL: http://vote-service:8083
  SEARCH_SERVICE_URL: http://search-service:8084
  STATS_SERVICE_URL: http://stats-service:8085
  CORS_ALLOWED_ORIGINS: http://frontend
  VOTE_THRESHOLD: "3"
  JWT_EXPIRATION: "86400000"
