spring.application.name=identity-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/salarydb?currentSchema=identity}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=identity
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET:ZmFrZS1kZXZlbG9wbWVudC1zZWNyZXQtZm9yLXN0dWRlbnQtY291cnNld29yay1vbmx5LTAwMDE=}
jwt.expiration=${JWT_EXPIRATION:86400000}
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
